# Form implementation generated from reading ui file 'nav_gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(598, 720)
        self.navigate_button = QtWidgets.QPushButton(parent=Dialog)
        self.navigate_button.setGeometry(QtCore.QRect(270, 390, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.navigate_button.setFont(font)
        self.navigate_button.setObjectName("navigate_button")
        self.stop_navigate_button = QtWidgets.QPushButton(parent=Dialog)
        self.stop_navigate_button.setGeometry(QtCore.QRect(270, 350, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stop_navigate_button.setFont(font)
        self.stop_navigate_button.setObjectName("stop_navigate_button")
        self.graphicsView = QtWidgets.QGraphicsView(parent=Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(70, 40, 480, 270))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.graphicsView.setFont(font)
        self.graphicsView.setObjectName("graphicsView")
        self.airsimConnect_button = QtWidgets.QPushButton(parent=Dialog)
        self.airsimConnect_button.setGeometry(QtCore.QRect(140, 500, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.airsimConnect_button.setFont(font)
        self.airsimConnect_button.setObjectName("airsimConnect_button")
        self.airsimDisconnect_button = QtWidgets.QPushButton(parent=Dialog)
        self.airsimDisconnect_button.setGeometry(QtCore.QRect(140, 550, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.airsimDisconnect_button.setFont(font)
        self.airsimDisconnect_button.setObjectName("airsimDisconnect_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.navigate_button.setText(_translate("Dialog", "Navigate"))
        self.stop_navigate_button.setText(_translate("Dialog", "Stop Navigate"))
        self.airsimConnect_button.setText(_translate("Dialog", "Connect"))
        self.airsimDisconnect_button.setText(_translate("Dialog", "Disconnect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
