# Form implementation generated from reading ui file 'sub_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1142, 600)
        self.navigate_button = QtWidgets.QPushButton(parent=Dialog)
        self.navigate_button.setGeometry(QtCore.QRect(220, 480, 81, 31))
        self.navigate_button.setObjectName("navigate_button")
        self.stop_navigate_button = QtWidgets.QPushButton(parent=Dialog)
        self.stop_navigate_button.setGeometry(QtCore.QRect(210, 430, 101, 31))
        self.stop_navigate_button.setObjectName("stop_navigate_button")
        self.graphicsView = QtWidgets.QGraphicsView(parent=Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(70, 160, 381, 261))
        self.graphicsView.setObjectName("graphicsView")
        self.mdiArea = QtWidgets.QMdiArea(parent=Dialog)
        self.mdiArea.setGeometry(QtCore.QRect(510, 90, 601, 481))
        self.mdiArea.setObjectName("mdiArea")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(550, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.addwindow_pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.addwindow_pushButton.setGeometry(QtCore.QRect(690, 30, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addwindow_pushButton.setFont(font)
        self.addwindow_pushButton.setObjectName("addwindow_pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.navigate_button.setText(_translate("Dialog", "Navigate"))
        self.stop_navigate_button.setText(_translate("Dialog", "Stop Navigate"))
        self.label.setText(_translate("Dialog", "Add Widnow"))
        self.addwindow_pushButton.setText(_translate("Dialog", "Add Window!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
